#!/usr/bin/env python3
"""Structural code search (ast-grep) integration.

Config and cached state live under the project's external directory
(``<state_dir>/ast-grep/``), never inside the customer repository -- same
hidden-state guarantee as PROJECT.md, discovery.json, and every other piece
of accelerator-owned per-project state.

Every function here is graceful when the ``ast-grep`` binary is not on
PATH: callers get an ``{"available": False, ...}`` result, never an
exception -- ``setup``/``run``/``refresh``/``doctor`` must not fail over an
optional tool.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

BINARY_NAME = "ast-grep"
STATE_DIRNAME = "ast-grep"
CONFIG_NAME = "sgconfig.yml"
RULES_DIRNAME = "rules"
INDEX_NAME = "index.json"

# embacc's own discovered language keys (see embacc_discover._detect_languages)
# mapped to ast-grep's `--lang` identifier. Live-confirmed identical strings
# for all four (`ast-grep run --lang <id> --pattern '$X' ...` accepted for
# each without an "unknown language" error).
LANGUAGE_MAP = {
    "cpp": "cpp",
    "c": "c",
    "python": "python",
    "rust": "rust",
}


def _pixi_env_binary() -> Path | None:
    """ast-grep installed as embacc's own pixi run-dependency, in the same
    environment as the running interpreter (conda/pixi layout) -- found
    without needing a separate `pixi global expose ast-grep` at all. Only
    consulted as a fallback when nothing named `ast-grep` is already on
    PATH, so a developer's own standalone install still takes priority."""
    env_root = Path(sys.executable).resolve().parent
    for candidate in (
        env_root / "Library" / "bin" / "ast-grep.exe",  # Windows conda layout
        env_root / "bin" / "ast-grep",  # Unix conda layout
        env_root / "ast-grep.exe",
        env_root / "ast-grep",
    ):
        if candidate.is_file():
            return candidate
    return None


def binary() -> str | None:
    found = shutil.which(BINARY_NAME)
    if found:
        return found
    sibling = _pixi_env_binary()
    return str(sibling) if sibling else None


def state_root(state_dir: Path) -> Path:
    return state_dir / STATE_DIRNAME


def config_path(state_dir: Path) -> Path:
    return state_root(state_dir) / CONFIG_NAME


def index_path(state_dir: Path) -> Path:
    return state_root(state_dir) / INDEX_NAME


def _version(exe: str) -> str | None:
    try:
        result = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=10, check=False)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    text = (result.stdout or result.stderr or "").strip()
    if not text:
        return None
    # `ast-grep --version` prints "ast-grep <version>"; callers already say
    # "ast-grep" themselves, so strip the redundant leading name if present.
    prefix = f"{BINARY_NAME} "
    return text[len(prefix):] if text.lower().startswith(prefix.lower()) else text


def ensure_config(state_dir: Path) -> Path:
    """Idempotently write the hidden sgconfig.yml + empty rule directory.
    Never touches the customer repository; never overwrites an existing
    config (a developer may hand-edit ruleDirs/custom rules there)."""
    root = state_root(state_dir)
    (root / RULES_DIRNAME).mkdir(parents=True, exist_ok=True)
    path = config_path(state_dir)
    if not path.is_file():
        path.write_text(
            "# Generated by embacc -- hidden project state, never installed into\n"
            "# the customer repository. Safe to hand-edit: embacc only creates this\n"
            "# file when absent and never overwrites it afterward.\n"
            f"ruleDirs:\n  - {RULES_DIRNAME}\n",
            encoding="utf-8",
        )
    return path


def languages_for(discovery: dict[str, Any]) -> list[str]:
    langs = discovery.get("languages") or {}
    return sorted(LANGUAGE_MAP[name] for name in langs if name in LANGUAGE_MAP)


def build_index(
    repo_root: Path, state_dir: Path, discovery: dict[str, Any], *, exe: str | None = None, timeout: float = 20.0
) -> dict[str, Any]:
    """Real per-language structural scan over the project's own source, not
    a placeholder: for each language embacc's discovery already found
    evidence for, run a near-universal ast-grep pattern (``$X``, which
    matches almost any single expression/identifier node) against the
    repository. A bare ``--version`` check would only prove the binary
    runs; this proves ast-grep's grammar can actually parse *this*
    project's real files. Cached to ``<state_dir>/ast-grep/index.json``.

    Intended for the less-frequent ``setup``/``refresh`` path; the hot
    ``run`` path should use `quick_status` instead (no subprocess beyond
    a PATH lookup).
    """
    exe = exe or binary()
    root = state_root(state_dir)
    root.mkdir(parents=True, exist_ok=True)
    result: dict[str, Any] = {"available": bool(exe), "binary": exe, "languages": {}}
    if not exe:
        (root / INDEX_NAME).write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
        return result

    result["version"] = _version(exe)
    ensure_config(state_dir)
    languages: dict[str, Any] = {}
    for lang in languages_for(discovery):
        try:
            proc = subprocess.run(
                [exe, "run", "--lang", lang, "--pattern", "$X", "--json=compact", str(repo_root)],
                capture_output=True, text=True, timeout=timeout, check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            languages[lang] = {"status": "error", "detail": str(exc)}
            continue
        if proc.returncode != 0:
            languages[lang] = {"status": "error", "detail": (proc.stderr or "").strip()[:300]}
            continue
        try:
            matches = json.loads(proc.stdout or "[]")
            match_count = len(matches) if isinstance(matches, list) else None
        except ValueError:
            match_count = None
        languages[lang] = {"status": "verified", "matches": match_count}
    result["languages"] = languages
    (root / INDEX_NAME).write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def load_index(state_dir: Path) -> dict[str, Any] | None:
    path = index_path(state_dir)
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def quick_status(state_dir: Path) -> dict[str, Any]:
    """Cheap check for the hot `embacc run` path: binary still on PATH,
    hidden config still present, plus whatever `build_index` (from the
    less-frequent setup/refresh path) last cached. Never re-runs the
    per-language scan itself -- that stays out of the launch-latency path."""
    exe = binary()
    cfg = config_path(state_dir)
    return {
        "available": bool(exe),
        "binary": exe,
        "config_path": str(cfg),
        "config_exists": cfg.is_file(),
        "cached_index": load_index(state_dir),
    }


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("state_dir", help="this project's external state directory")
    parser.add_argument("--repo-root", help="required with --build-index")
    parser.add_argument("--build-index", action="store_true", help="run a full per-language index against --repo-root")
    args = parser.parse_args()
    state_dir = Path(args.state_dir)
    if args.build_index:
        if not args.repo_root:
            parser.error("--build-index requires --repo-root")
        discovery_path = state_dir / "discovery.json"
        try:
            discovery = json.loads(discovery_path.read_text(encoding="utf-8")) if discovery_path.is_file() else {}
        except (OSError, ValueError):
            discovery = {}
        result = build_index(Path(args.repo_root), state_dir, discovery)
    else:
        result = quick_status(state_dir)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
