#!/usr/bin/env python3
"""Repository-local resources used by ``embacc install`` and native skills."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path

PACKAGE_VERSION = "2.6.0"
TOOLS = ("codex", "claude", "opencode", "pi")
GENERATED = "<!-- generated by embacc install; edit .agents/skills instead -->"
FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)
NAME_RE = re.compile(r"^name:\s*(.+?)\s*$", re.M)
DESC_RE = re.compile(r"^description:\s*(.+?)\s*$", re.M)


class ResourceError(RuntimeError):
    pass


def parse_tools(raw: str) -> tuple[str, ...]:
    values = {item.strip().lower() for item in raw.split(",") if item.strip()}
    unknown = sorted(values - set(TOOLS))
    if unknown:
        raise ResourceError("unknown tools: " + ", ".join(unknown))
    return tuple(tool for tool in TOOLS if tool in values)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def path_issue(root: Path, path: Path) -> str | None:
    """Return a reason if *path* escapes *root* or traverses a symlink."""
    root = root.resolve()
    try:
        relative = path.relative_to(root)
    except ValueError:
        return "path is outside its root"

    cursor = root
    for index, part in enumerate(relative.parts):
        cursor /= part
        if cursor.is_symlink():
            return f"symbolic-link component: {cursor.relative_to(root)}"
        if index < len(relative.parts) - 1 and cursor.exists() and not cursor.is_dir():
            return f"non-directory parent: {cursor.relative_to(root)}"
    try:
        path.resolve(strict=False).relative_to(root)
    except ValueError:
        return "resolved path escapes its root"
    return None


def skill_metadata(path: Path) -> tuple[str, str]:
    """Parse Embacc's deliberately small, host-safe SKILL.md frontmatter subset.

    Descriptions are required to be JSON-style double-quoted strings. JSON
    strings are valid YAML scalars, and enforcing this subset prevents a colon
    in a description from silently turning valid-looking metadata into invalid
    YAML for Pi/Codex/other hosts.
    """
    text = path.read_text(encoding="utf-8")
    frontmatter = FM_RE.match(text)
    if not frontmatter:
        raise ResourceError(f"missing YAML frontmatter: {path}")
    name_match = NAME_RE.search(frontmatter.group(1))
    description_match = DESC_RE.search(frontmatter.group(1))
    if not name_match or not description_match:
        raise ResourceError(f"missing skill name/description: {path}")

    raw_name = name_match.group(1).strip()
    if raw_name.startswith(('"', "'")):
        try:
            name = json.loads(raw_name) if raw_name.startswith('"') else raw_name[1:-1]
        except (ValueError, json.JSONDecodeError) as exc:
            raise ResourceError(f"invalid quoted skill name in {path}: {exc}") from exc
    else:
        name = raw_name

    raw_description = description_match.group(1).strip()
    if not raw_description.startswith('"'):
        raise ResourceError(
            f"skill description must be double-quoted YAML/JSON text: {path}"
        )
    try:
        description = json.loads(raw_description)
    except (ValueError, json.JSONDecodeError) as exc:
        raise ResourceError(f"invalid quoted skill description in {path}: {exc}") from exc
    if not isinstance(name, str) or not isinstance(description, str) or not description.strip():
        raise ResourceError(f"invalid skill name/description values: {path}")
    return name.strip(), description.strip()


def _yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def canonical_skills(source_root: Path) -> list[Path]:
    root = source_root / ".agents" / "skills"
    if root.is_symlink() or not root.is_dir():
        raise ResourceError(f"missing/unsafe canonical skills directory: {root}")
    skills = sorted(root.glob("*/SKILL.md"))
    if not skills:
        raise ResourceError("no canonical skills found")
    for skill in skills:
        if skill.is_symlink() or not skill.is_file():
            raise ResourceError(f"unsafe canonical skill: {skill}")
        name, _ = skill_metadata(skill)
        if name != skill.parent.name:
            raise ResourceError(f"skill name {name!r} does not match directory {skill.parent.name!r}")
    return skills


def canonical_skill_names(source_root: Path) -> tuple[str, ...]:
    return tuple(skill_metadata(path)[0] for path in canonical_skills(source_root))


def _static_templates(source_root: Path, selected: tuple[str, ...]) -> dict[Path, Path]:
    result: dict[Path, Path] = {}
    templates = source_root / "tooling" / "templates"
    for tool in selected:
        root = templates / tool
        # Codex needs no extra template: AGENTS.md and .agents/skills are native.
        if tool == "codex" and not root.exists():
            continue
        if root.is_symlink() or not root.is_dir():
            raise ResourceError(f"missing/unsafe template directory: {root}")
        for source in sorted(root.rglob("*")):
            if source.is_symlink():
                raise ResourceError(f"symbolic links are forbidden in templates: {source}")
            if not source.is_file():
                continue
            relative = source.relative_to(root)
            if relative in result:
                raise ResourceError(f"template target collision: {relative}")
            result[relative] = source
    return result


def generated_adapters(source_root: Path, selected: tuple[str, ...]) -> dict[Path, str]:
    files: dict[Path, str] = {}
    for skill in canonical_skills(source_root):
        name, description = skill_metadata(skill)
        adapter = f"acc-{name}"
        quoted = _yaml_quote(description)
        if "claude" in selected:
            files[Path(f".claude/skills/{adapter}/SKILL.md")] = (
                f"---\nname: {adapter}\ndescription: {quoted}\n---\n\n{GENERATED}\n\n"
                f"Read `.agents/skills/{name}/SKILL.md` and follow it. Obey `AGENTS.md`.\n"
            )
        if "opencode" in selected:
            files[Path(f".opencode/commands/{adapter}.md")] = (
                f"---\ndescription: {quoted}\n---\n\n{GENERATED}\n\n"
                f"Load and execute `{name}` for this request:\n\n$ARGUMENTS\n"
            )
    return files


def materialize_resources(source_root: Path, destination: Path, selected: tuple[str, ...]) -> None:
    """Write the complete desired repository payload into *destination*."""
    source_root = source_root.resolve()
    destination.mkdir(parents=True, exist_ok=True)
    seen: set[Path] = set()

    def copy(relative: Path, source: Path) -> None:
        if relative in seen:
            raise ResourceError(f"resource target collision: {relative}")
        seen.add(relative)
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)

    agents = source_root / "AGENTS.md"
    if agents.is_symlink() or not agents.is_file():
        raise ResourceError(f"missing/unsafe AGENTS.md: {agents}")
    copy(Path("AGENTS.md"), agents)

    for skill in canonical_skills(source_root):
        copy(Path(".agents/skills") / skill.parent.name / "SKILL.md", skill)

    for relative, source in _static_templates(source_root, selected).items():
        copy(relative, source)

    for relative, content in generated_adapters(source_root, selected).items():
        if relative in seen:
            raise ResourceError(f"generated adapter collides with template: {relative}")
        seen.add(relative)
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def materialize_core_skills(source_root: Path, destination: Path) -> None:
    for skill in canonical_skills(source_root.resolve()):
        target = destination / ".agents" / "skills" / skill.parent.name / "SKILL.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(skill, target)
